### ISSUE TITLE
Does not work when fish_greeting is disabled

### ISSUE THREAD

**Issue by derekstavis** [oh-my-fish/theme-batman#1]
Originally seen on oh-my-fish/oh-my-fish#249.

The issue here is that when `fish_greeting` is disabled the helper color functions aren't defined.

**Comment by MosheBerman** [comment]
How might this be fixed?

**Comment by oz117** [comment]
Hey! If you are still looking for a solution what I did is disable fish_greeting by putting 
`set fish_greeting ""` inside the config file in `~/.config/fish/config.fish`

**Comment by MosheBerman** [comment]
Thanks!

**Comment by sagebind** [comment]
This actually causes a slew of issues, as seen in https://github.com/oh-my-fish/oh-my-fish/issues/483. I recommend moving helper functions to their own files in a `functions` directory. `fish_greeting` is meant to be user-overridable, so using it for initialization is unreliable anyway. 

This is not the only theme to have this issue. I will be opening issues in other themes using `fish_greeting` in this way.

**Comment by palindrom615** [comment]
I want to merge my fork that fixed this Issue. 

I moved `fst`, `snd`... functions declared at `fish_greeting.fish` to `fish_prompt.fish` and hard coded original fish_greeting.

yeah I know that's quite Ignorant and not the driest way of my code, but I'm not sure it is the right way to decalre something in a file which has no guarantee for executing ...

**Comment by bobthecow** [comment]
This should be fixed by #5!
